/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package p1.ek.bookstorev2;

import org.junit.jupiter.api.Test;

import com.p1.ek.bookstorev2.BookStoreAPIDriver;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        BookStoreAPIDriver classUnderTest = new BookStoreAPIDriver();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    // @Test 
}
