/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.p1.ek.bookstorev2;

import com.p1.ek.model.objfiles.Book;

import io.javalin.Javalin;
import io.javalin.core.JavalinConfig;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.p1.ek.controller.AuthorService;
import com.p1.ek.controller.BookService;
import com.p1.ek.controller.GenreService;

public class BookStoreAPIDriver {

    private static Logger log = LogManager.getLogger(BookStoreAPIDriver.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        log.info("Wassup");

        BookService bs = new BookService();
        AuthorService as = new AuthorService();
        GenreService gs = new GenreService();

        

        Javalin app = Javalin.create(JavalinConfig::enableCorsForAllOrigins).start(7070);

        
        // Get all books
        app.get("/books", ctx -> ctx.json(bs.readRecords()));
        // app.get("/authors", ctx -> ctx.json(as.readRecords()));
        // app.get("/genres", ctx -> ctx.json(gs.readRecords()));

        // Get a book
        app.get("/books/{bookId}", ctx -> ctx.json(bs.readRecord(Integer.parseInt(ctx.pathParam("bookId")))));

        // Post a book
        app.post("books", ctx -> {
            ObjectMapper mapper = new ObjectMapper();
            Book newBook = mapper.readValue(ctx.body(), Book.class);
            bs.createRecord(newBook);
        });

        app.get("/authors", ctx -> ctx.json(as.readRecords()));
        // System.out.println(new BookStoreAPIDriver().getGreeting());

        app.get("/genres", ctx -> ctx.json(gs.readRecords()));

        // app.post("/login", ctx -> ctx.json());
    }
}
