/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.p1.ek.bookstorev2;

import io.javalin.Javalin;
import io.javalin.core.JavalinConfig;
import com.p1.ek.controller.BookService;

public class BookStoreAPIDriver {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        BookService bs = new BookService();
        Javalin app = Javalin.create(JavalinConfig::enableCorsForAllOrigins).start(7070);
        app.get("/books", ctx -> ctx.json(bs.readRecords()));
        // System.out.println(new BookStoreAPIDriver().getGreeting());
    }
}
